let menuParticleContainer = null;
let menuEmitter = null;
let lastParticleTime = Date.now();
function We0h(t) {
    BLg_.V && (BLg_.V = !1,
    BLg_.Ui()),
    D.JyWD(0, 0, Hhar, T0mk, FouV.St),
    null != BLg_.o1 ? (mainMenu_avatar_opacity < 1 && (mainMenu_avatar_opacity += .2),
    s = D.JjQ2(BLg_.a1),
    D.Dm9f(BLg_.o1, 0, 0, 0, 550 / s, 0, 0, 0, mainMenu_avatar_opacity)) : mainMenu_avatar_opacity = 0,
    FouV.wt = 1.5,
    FouV.Dt = FouV.wt / BLg_.Mi,
    D.Dm9f(BLg_.xi[1], (ZcYj - 480 * FouV.wt) / 2, 90, 0, FouV.Dt),
    (new Date).getFullYear();
    var s = .995 * Hhar
      , e = .99 * T0mk;
/*
    D.C_wB('<a onclick="globalUnlockPage()" href="#">Achievements ✹ ' + FouV.It + " / " + FouV.Ct + "</a>", 15, e - 42, "OkQn", "#9aaff3"),
    D.C_wB('<a onclick="globalQuitGame()" href="#">Quit </a>', s, e - 42, "KrcT", "#5A77D8"),
    CrdD.j0 < 0 ? (D.C_wB("Sorry. The unlock code has been changed. Clear Stage Mode on Difficult to reveal it.", s / 2, e - 204, "Itbg", "#FFF"),
    D.C_wB("✹", s / 2, e - 150, "Itbg", "#FFF"),
    CrdD.j0++) : 0 < CrdD.j0 && (D.C_wB("Unlock code accepted!", s / 2, e - 204, "Itbg", "#FFF"),
    D.C_wB("✹", s / 2, e - 150, "Itbg", "#FFF"),
    CrdD.j0--),
*/

    FouV.wt = 1.4,
    FouV.Dt = FouV.wt / BLg_.Mi,
    FouV.Kt = (ZcYj - 305 * FouV.wt) / 2,
    FouV.$t = 165 * FouV.wt,
    D.Dm9f(BLg_.e1[1], FouV.Kt, FouV.$t, 0, FouV.Dt);
    let i = -1;
    0 == (i = FouV.Jt >= FouV.Kt + 13 * FouV.wt && FouV.Jt <= FouV.Kt + 288 * FouV.wt && (FouV.Ht >= FouV.$t + -2 * FouV.wt && FouV.Ht <= FouV.$t + 21 * FouV.wt && (i = 0),
    FouV.Ht >= FouV.$t + 25 * FouV.wt && FouV.Ht <= FouV.$t + 48 * FouV.wt && (i = 1),
    FouV.Ht >= FouV.$t + 52 * FouV.wt && FouV.Ht <= FouV.$t + 75 * FouV.wt && (i = 2),
    FouV.Ht >= FouV.$t + 79 * FouV.wt && FouV.Ht <= FouV.$t + 102 * FouV.wt && (i = 3),
    FouV.Ht >= FouV.$t + 105 * FouV.wt && FouV.Ht <= FouV.$t + 128 * FouV.wt && (i = 4),
    FouV.Ht >= FouV.$t + 133 * FouV.wt) && FouV.Ht <= FouV.$t + 156 * FouV.wt ? 5 : i) ? D.Dm9f(BLg_.e1[2], FouV.Kt + 45 * FouV.wt, FouV.$t + -2 * FouV.wt, 0, FouV.Dt, 0, 0, 0, .3) : 1 == i ? D.Dm9f(BLg_.e1[3], FouV.Kt + 31 * FouV.wt, FouV.$t + 25 * FouV.wt, 0, FouV.Dt, 0, 0, 0, .3) : 2 == i ? D.Dm9f(BLg_.e1[4], FouV.Kt + 13 * FouV.wt, FouV.$t + 52 * FouV.wt, 0, FouV.Dt, 0, 0, 0, .3) : 3 == i ? D.Dm9f(BLg_.e1[5], FouV.Kt + 13 * FouV.wt, FouV.$t + 79 * FouV.wt, 0, FouV.Dt, 0, 0, 0, .3) : 4 == i ? D.Dm9f(BLg_.e1[38], FouV.Kt + 46 * FouV.wt, FouV.$t + 105 * FouV.wt, 0, FouV.Dt, 0, 0, 0, .3) : 5 == i && D.Dm9f(BLg_.e1[6], FouV.Kt + 55 * FouV.wt, FouV.$t + 133 * FouV.wt, 0, FouV.Dt, 0, 0, 0, .3),
    -1 < i && FouV.F && (FouV.F = !1,
    0 == i && (CrdD.Na = 512),
    1 == i && (CrdD.Na = 1024),
    2 == i && (CrdD.Na = 2048),
    3 == i && (CrdD.Na = 4096),
    4 == i && (CrdD.Na = 8192),
    5 == i) && (CrdD.Na = 16384),
    0 == t.$s ? D.Dm9f(BLg_.e1[2], FouV.Kt + 45 * FouV.wt, FouV.$t + -2 * FouV.wt, 0, FouV.Dt) : 1 == t.$s ? D.Dm9f(BLg_.e1[3], FouV.Kt + 31 * FouV.wt, FouV.$t + 25 * FouV.wt, 0, FouV.Dt) : 2 == t.$s ? D.Dm9f(BLg_.e1[4], FouV.Kt + 13 * FouV.wt, FouV.$t + 52 * FouV.wt, 0, FouV.Dt) : 3 == t.$s ? D.Dm9f(BLg_.e1[5], FouV.Kt + 13 * FouV.wt, FouV.$t + 79 * FouV.wt, 0, FouV.Dt) : 4 == t.$s ? D.Dm9f(BLg_.e1[38], FouV.Kt + 46 * FouV.wt, FouV.$t + 105 * FouV.wt, 0, FouV.Dt) : 5 == t.$s && D.Dm9f(BLg_.e1[6], FouV.Kt + 55 * FouV.wt, FouV.$t + 133 * FouV.wt, 0, FouV.Dt),
    IAlU(t),
    0 < t.de && (t.$s = t.$s - 1,
    t.$s < 0) && (t.$s = 5),
    0 < t.R0 && (t.$s = (t.$s + 1) % 6),
    (0 < t.attack || FouV.si || 0 != (512 & CrdD.Ua) || 0 != (1024 & CrdD.Ua) || 0 != (2048 & CrdD.Ua) || 0 != (4096 & CrdD.Ua) || 0 != (8192 & CrdD.Ua) || 0 != (16384 & CrdD.Ua)) && (t.$s < 7 && XYSz.D(1, 1),
    (0 == t.$s || FouV.si && "vs" == FouV.hi || 0 != (512 & CrdD.Ua)) && (t.$s = 0,
    t.fo = 0,
    t.H0 = 3,
    t.Ce = 100,
    t.Ie = 1,
    BLg_.se()),
    1 != t.$s && 0 == (1024 & CrdD.Ua) || (t.$s = 1,
    t.fo = 0,
    t.H0 = 3,
    t.Ce = 100,
    t.Ie = 1,
    BLg_.se()),
    2 != t.$s && 0 == (2048 & CrdD.Ua) || (-1 == t.ve && (t.ve = 0),
    t.$s = 2,
    t.H0 = 20,
    t.Ce = 0,
    t.Ie = 0,
    CrdD.j0 = 0,
    BLg_.se()),
    3 != t.$s && 0 == (4096 & CrdD.Ua) || (-1 == t.ve && (t.ve = 0),
    t.$s = 3,
    t.H0 = 120,
    t.Ce = 0,
    t.Ie = 0,
    CrdD.j0 = 0,
    BLg_.se()),
    4 != t.$s && 0 == (8192 & CrdD.Ua) || (-1 == t.ve && (t.ve = 0),
    t.$s = 4,
    t.fo = 0,
    t.H0 = 3,
    t.Ce = 100,
    t.Ie = 1,
    CrdD.j0 = 0,
    BLg_.se()),
    5 != t.$s && 0 == (16384 & CrdD.Ua) || (t.ve = 0,
    t.$s = 5,
    t.H0 = 2,
    t.rh = 1,
    CrdD.j0 = 0,
    BLg_.se()),
    t.$s)
}